timeout: 3600s # Cache misses are slow to rebuild
substitutions:
  # Bump the version if you make changes to `ci/Dockerfile
  _BUILD_IMAGE: gcr.io/uplink-test-cluster-174313/pairing-ci:v2
options:
  machineType: N1_HIGHCPU_8
steps:
  # Build uplink docker image with kaniko
  - id: "build-ci-base-image"
    name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      set -euxo pipefail
      if ! docker pull $_BUILD_IMAGE; then
        docker build ci --tag $_BUILD_IMAGE
        docker push $_BUILD_IMAGE
      fi
  - id: "build"
    name: $_BUILD_IMAGE
    waitFor: ["build-ci-base-image"]
    entrypoint: bash
    args:
    - '-c'
    - |
      set -euxo pipefail
      mkdir ./bin
      stack install \
        --no-terminal \
        --fast \
        --test \
        --no-run-tests \
        --local-bin-path .
  - id: "test"
    name: $_BUILD_IMAGE
    entrypoint: bash
    waitFor: ['build']
    args:
    - '-c'
    - |
      set -euxo pipefail
      stack test pairing:pairing-tests --no-terminal --system-ghc
