name:        pairing
version:     0.5.0
synopsis:    Bilinear pairings
description: Optimal Ate pairing over Barreto-Naehrig curves
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/pairing
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - DataKinds
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedLists
  - PatternSynonyms
  - StandaloneDeriving
  - TypeFamilyDependencies

dependencies:
  - base >= 4.10 && < 5
  - protolude >= 0.2 && < 0.3
  - bytestring
  - elliptic-curve >= 0.3 && < 0.4
  - errors
  - galois-field >= 1 && < 2
  - groups
  - MonadRandom
  - tasty-quickcheck

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -freverse-errors
  - -O2
  - -Wall

library:
  exposed-modules:
    - Data.Pairing
    - Data.Pairing.BLS12381
    - Data.Pairing.BLS48581
    - Data.Pairing.BN254
    - Data.Pairing.BN254A
    - Data.Pairing.BN254B
    - Data.Pairing.BN254C
    - Data.Pairing.BN254D
    - Data.Pairing.BN462
    - Data.Pairing.Hash
  other-modules:
    - Data.Pairing.Ate
  source-dirs:
    - src

tests:
  pairing-tests:
    main: Main
    dependencies:
      - pairing
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    source-dirs:
      - test

benchmarks:
  pairing-benchmarks:
    main: Main
    dependencies:
      - criterion
      - pairing
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    source-dirs:
      - bench
