name:        pairing
version:     0.3.1
synopsis:    Optimal ate pairing over Barreto-Naehrig curves
description: Optimal ate pairing over Barreto-Naehrig curves
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/pairing
category:    Cryptography

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
  # Prelude
  - base >= 4.7 && < 5
  - protolude >= 0.2
  - arithmoi >= 0.8
  - binary
  - bytestring
  - errors
  - galois-field >= 0.2
  - integer-logarithms
  - memory
  - MonadRandom
  - QuickCheck
  - random
  - wl-pprint-text

library:
  source-dirs: src

  ghc-options:
    -fwarn-tabs
    -fwarn-incomplete-patterns
    -fwarn-incomplete-record-updates
    -fwarn-redundant-constraints
    -fwarn-implicit-prelude
    -fwarn-overflowed-literals
    -fwarn-orphans
    -fwarn-identities
    -fwarn-dodgy-exports
    -fwarn-dodgy-imports
    -fwarn-duplicate-exports
    -fwarn-overlapping-patterns
    -fwarn-missing-fields
    -fwarn-missing-methods
    -fwarn-missing-signatures
    -fwarn-noncanonical-monad-instances
    -fwarn-unused-pattern-binds
    -fwarn-unused-type-patterns
    -fwarn-unrecognised-pragmas
    -fwarn-wrong-do-bind
    -fno-warn-name-shadowing
    -fno-warn-unused-binds
    -fno-warn-unused-matches
    -fno-warn-unused-do-bind
    -Wmissing-export-lists

  default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances
    - FlexibleContexts
    - ScopedTypeVariables
    - RankNTypes
    - DataKinds
    - DeriveAnyClass
    - DeriveFunctor
    - DeriveGeneric
    - GeneralizedNewtypeDeriving
    - MultiParamTypeClasses
    - TypeApplications

  exposed-modules:
    - Pairing.Params
    - Pairing.Fq
    - Pairing.Fr
    - Pairing.Point
    - Pairing.Group
    - Pairing.Pairing
    - Pairing.Jacobian
    - Pairing.CyclicGroup
    - Pairing.Hash
    - Pairing.Serialize
    - Pairing.ByteRepr
    - Pairing.Modular

tests:
  pairing-tests:
    main: Driver.hs
    source-dirs:
      - src
      - tests
    dependencies:
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-quickcheck
    default-extensions:
      - LambdaCase
      - RecordWildCards
      - OverloadedStrings
      - NoImplicitPrelude
      - FlexibleInstances
      - FlexibleContexts
      - ScopedTypeVariables
      - RankNTypes
      - DataKinds
      - DeriveAnyClass
      - DeriveFunctor
      - DeriveGeneric
      - MultiParamTypeClasses
      - TypeApplications
      - TypeSynonymInstances

benchmarks:
  pairing-benchmarks:
    main: Main.hs
    source-dirs:
      - src
      - bench
    dependencies:
      - criterion
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-hunit
      - tasty-quickcheck
    default-extensions:
      - LambdaCase
      - RecordWildCards
      - OverloadedStrings
      - NoImplicitPrelude
      - FlexibleInstances
      - FlexibleContexts
      - ScopedTypeVariables
      - RankNTypes
      - DataKinds
      - DeriveAnyClass
      - DeriveFunctor
      - DeriveGeneric
      - MultiParamTypeClasses
      - TypeApplications
