resolver: lts-13.19
extra-deps:
  - git: https://github.com/adjoint-io/galois-field.git
    commit: 19567de8e4b512e123242a55a4d93b3f646cbbe7
  - git: https://github.com/adjoint-io/elliptic-curve.git
    commit: 14cb090e2513060fecd0403e5dabebb06357f709
  - git: https://github.com/chessai/semirings.git
    commit: 8b6c208f3d771fae066fcb637da492e7251a8e50
  - git: https://github.com/adjoint-io/poly.git
    commit: 1eb5b7a820a685de7c07576e028dee332e3382f8
